### ISSUE TITLE
Export not working with custom date fields 

### ISSUE THREAD

**Issue by flyingdutchman22** [DiscipleTools/disciple-tools-list-exports#13]
Hello! We have added several custom date fields which we would like to be able to export; however, when we try to use the "Export CSV" button, it just spins. When none of the date fields are selected, it works fine. Any idea what we can do to counteract this?

**Comment by corsacca** [comment]
Hey @flyingdutchman22 
Thanks for helping narrow down what was causing the issue.
I've push a fix: https://github.com/DiscipleTools/disciple-tools-list-exports/commit/180c052ad5c8d6ab74bf9847bf1c990d56de5ccd

v1.9.1 should work for you

**Comment by flyingdutchman22** [comment]
Amazing! Can confirm issue solved. Thanks so much!

**Comment by corsacca** [comment]
Awesome. Thanks!
