### ISSUE TITLE
Locations not included in CSV exports 

### ISSUE THREAD

**Issue by flyingdutchman22** [DiscipleTools/disciple-tools-list-exports#14]
Hello! Just found that location fields are not being included in CSV list exports; the column header is there but all the rows are blank. This will be important for sorting data by location. 

Thanks!

**Comment by corsacca** [comment]
Thanks @flyingdutchman22, we'll have a look.

**Comment by flyingdutchman22** [comment]
@corsacca Yes, just updated the plugin and it works! Problem solved. Thanks so much for your work on this; this tool is incredibly valuable to us and your work is appreciated.
