### ISSUE TITLE
Exports don't work on smaller screen dimensions

### ISSUE THREAD

**Issue by prykon** [DiscipleTools/disciple-tools-list-exports#9]
**Bug:**
If a user is using a smaller screen dimension, the class names that are being referenced to scrape table data change and nothing gets found/exported.

**How to reproduce:**
1. Open contacts page
2. Reduce screen size so that the responsive class names activate
3. Try to export by clicking `List Exports > csv list` (divs that should contain export data are empty)

I don't know how many people are trying to export from a small screen (exporting CSVs doesn't seem to be relevant in mobile), but maybe this warrants a fix.

**Comment by corsacca** [comment]
@prykon good catch. Yes this should be fixed.

**Comment by corsacca** [comment]
Fixed in https://github.com/DiscipleTools/disciple-tools-list-exports/pull/10
